name: CDK Build and Deploy Infrastructure (Prod)

on:
    push:
        branches: [prod]
    pull_request:
        branches: [prod]
    repository_dispatch:
        types: [frontend_source_updated_prod]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: prod

            # - name: Install jq
            #   run: |
            #       sudo apt-get update
            #       sudo apt-get install -y jq

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Deploy to AWS (Prod)
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  TMDB_API_ACCESS_TOKEN_PROD: ${{ secrets.TMDB_API_ACCESS_TOKEN_PROD }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  DEV_WEBSITE_USERNAME: ${{ secrets.DEV_WEBSITE_USERNAME }}
                  DEV_WEBSITE_PASSWORD: ${{ secrets.DEV_WEBSITE_PASSWORD }}
              run: |
                  npm run bootstrap:prod
                  npm run deploy:prod
